import { useMemo, useState } from 'react';
import type { ProjectRecord } from '../domain/project/types';
import { createScheduleReport, scheduleReportToCsv, type ScheduleReportKind } from '../domain/reporting/scheduleReports';
import type { ScheduleResult } from '../domain/schedule/types';
import { downloadTextFile, printScheduleReport } from '../infrastructure/reportExport';

interface ScheduleReportsPanelProps { project: ProjectRecord; result?: ScheduleResult; }

const REPORT_CATALOG: Array<{ kind: ScheduleReportKind; title: string; description: string; definition: string }> = [
  { kind: 'critical-path', title: 'Critical path', description: 'Driving and zero-float activities controlling completion.', definition: 'Activities classified critical by the current float threshold and network calculation.' },
  { kind: 'float', title: 'Float analysis', description: 'Total and free float with criticality classification.', definition: 'Calendar-aware schedule flexibility calculated from early and late dates.' },
  { kind: 'logic', title: 'Logic quality', description: 'Open ends, warnings, constraints, and relationship findings.', definition: 'Network-quality exceptions generated by the deterministic CPM engine.' },
  { kind: 'milestones', title: 'Milestone outlook', description: 'Project commitments, deadlines, and calculated dates.', definition: 'All milestone activities with status-date and baseline context.' },
  { kind: 'look-ahead', title: 'Look-ahead', description: 'Activities occurring inside a configurable forward window.', definition: 'Activities whose calculated work intersects the selected period after the project status date.' }
];

export function ScheduleReportsPanel({ project, result }: ScheduleReportsPanelProps) {
  const [kind, setKind] = useState<ScheduleReportKind>('critical-path');
  const [lookAheadDays, setLookAheadDays] = useState(21);
  const selected = REPORT_CATALOG.find((item) => item.kind === kind)!;
  const report = useMemo(() => result ? createScheduleReport(kind, project, result, { lookAheadDays }) : undefined, [kind, lookAheadDays, project, result]);
  const completeness = result ? Math.max(0, Math.round((project.activities.length - result.warnings.filter((warning) => warning.severity === 'error').length) / Math.max(1, project.activities.length) * 100)) : 0;

  return (
    <div className="report-catalog-workspace">
      <section className="surface report-catalog" aria-labelledby="reports-title">
        <div className="surface-heading"><div><p className="eyebrow">Phase H · standardized report surfaces</p><h2 id="reports-title">Report catalog</h2><p>Select a defined report, configure its scope, review provenance, then export from the same immutable project revision.</p></div></div>
        <nav aria-label="Schedule report catalog">{REPORT_CATALOG.map((item) => <button key={item.kind} className={kind === item.kind ? 'active' : ''} type="button" onClick={() => setKind(item.kind)} aria-current={kind === item.kind ? 'page' : undefined}><strong>{item.title}</strong><span>{item.description}</span></button>)}</nav>
      </section>

      <section className="surface report-preview" aria-labelledby="report-preview-title">
        <div className="surface-heading phase-toolbar"><div><p className="eyebrow">Configured evidence preview</p><h2 id="report-preview-title">{selected.title}</h2><p>{selected.definition}</p></div><div className="toolbar-group wrap">{kind === 'look-ahead' ? <label>Forward window<input type="number" min={1} max={365} value={lookAheadDays} onChange={(event) => setLookAheadDays(Number(event.target.value))} /> days</label> : null}<button className="button button-secondary" type="button" disabled={!report} onClick={() => report && downloadTextFile(scheduleReportToCsv(report), `${kind}-r${project.revision}.csv`, 'text/csv;charset=utf-8')}>Download CSV</button><button className="button button-primary" type="button" disabled={!report} onClick={() => report && printScheduleReport(report)}>Print / PDF</button></div></div>
        {!report ? <div className="empty-state">A valid schedule calculation is required.</div> : <>
          <div className="report-evidence-strip" role="status"><span><small>Revision</small><strong>{report.provenance.projectRevision}</strong></span><span><small>Status date</small><strong>{report.provenance.statusDate}</strong></span><span><small>Engine</small><strong>{report.provenance.engineVersion}</strong></span><span><small>Rows</small><strong>{report.rows.length}</strong></span><span><small>Completeness</small><strong>{completeness}%</strong></span></div>
          <details className="report-definition" open><summary>Definition, source, and calculation context</summary><dl><dt>Definition</dt><dd>{selected.definition}</dd><dt>Source</dt><dd>Project revision {project.revision}, status date {project.statusDate}, CPM engine {report.provenance.engineVersion}</dd><dt>Calculation time</dt><dd>{report.provenance.calculatedAt}</dd><dt>Generation time</dt><dd>{report.provenance.generatedAt}</dd><dt>Completeness</dt><dd>{completeness}% based on current error-level schedule findings.</dd></dl></details>
          <div className="report-table-scroll" tabIndex={0} aria-label={`Scrollable ${selected.title} report table`}><table className="report-table"><thead><tr>{report.columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{report.rows.map((row, index) => <tr key={`${report.id}-${index}`}>{report.columns.map((column) => <td key={column.key}>{String(row[column.key] ?? '')}</td>)}</tr>)}</tbody></table></div>
        </>}
      </section>
    </div>
  );
}
